# Generated by Django 4.1.3 on 2024-08-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_security_app', '0002_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
